name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
            ubuntu-latest, # x86_64
            ubuntu-24.04-arm, # arm
            macos-26-intel, # x86_64
            macos-26, # arm
            windows-latest, # x86_64
          ]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt-get install -y libasound2-dev pkg-config
          if [[ "${{ matrix.setup }}" == "linux-jack" ]]; then
            sudo apt-get install -y libjack-jackd2-dev
          fi

      - name: Intall Deno
        uses: denoland/setup-deno@v2

      - if: runner.os == 'Linux'
        name: Run docs lint
        run: deno doc --lint mod.ts
      - if: runner.os == 'Linux'
        name: Run tests Linux
        run: export CARGO_TARGET_DIR=target && export RUST_LIB_PATH=$CARGO_TARGET_DIR/debug && deno task build && mv $CARGO_TARGET_DIR/debug/libdeno_webmidi_ffi.so $CARGO_TARGET_DIR/debug/libdeno_webmidi_ffi_$(uname -m).so && deno test -A

      # NOTE: make macos testing easier for users
      - if: runner.os == 'macOS'
        name: Run tests MacOs
        run: export CARGO_TARGET_DIR=target && export RUST_LIB_PATH=$CARGO_TARGET_DIR/debug && deno task build && mv $CARGO_TARGET_DIR/debug/libdeno_webmidi_ffi.dylib $CARGO_TARGET_DIR/debug/libdeno_webmidi_ffi_$(uname -m).dylib && deno test -A

      - if: runner.os == 'Windows'
        name: Run tests Windows
        run: $env:CARGO_TARGET_DIR='target'; deno task test
